Firma HERMLOK istnieje na rynku od 1995 roku. Specjalizujemy siê w budowie kominków. Aby sprostaæ wymaganiom klientów, oferujemy bardzo du¿y wybór obudów od rustykalnych poprzez klasyczne do bardzo nowoczesnych. Zajmujemy siê równie¿ dystrybucj± ciep³ego powietrza, prowadzimy serwis oraz doradztwo techniczne. Sprzedajemy wk³ady kominkowe:

- francuskie Fonte Flamme 

- norweskie DOVRE
 
- polskie HAJDUK 